language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
    - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 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
  local_dir: build
  on:
    branch: master